version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: parking
      MONGO_INITDB_ROOT_PASSWORD: pocParking

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8085
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: parking
      ME_CONFIG_MONGODB_ADMINPASSWORD: pocParking
      ME_CONFIG_MONGODB_URL: mongodb://parking:pocParking@mongo:27017/
      ME_CONFIG_BASICAUTH: false
